OPENAI_API_KEY='sk-proj-RDZaDlF6qGZZF9sHf6umT3BlbkFJZ6LtrsjATEM3ds0M0fNS'

"PINATA_API_KEY" = "b3f3190b944df6f6fd1c"
"PINATA_SECRET_API_KEY" = "8117cb80d31a8f056b7b61e2701f5befa94297757d79c987ba05dfb001b252c9"
"PINATA_JWT_TOKEN" = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI2ZmE4NDcwMC00ZmEwLTQzYzItOGRjNS1jNzJhMTA3NTczYzUiLCJlbWFpbCI6IjB4ZGFvbUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJpZCI6IkZSQTEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX0seyJpZCI6Ik5ZQzEiLCJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MX1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiYjNmMzE5MGI5NDRkZjZmNmZkMWMiLCJzY29wZWRLZXlTZWNyZXQiOiI4MTE3Y2I4MGQzMWE4ZjA1NmI3YjYxZTI3MDFmNWJlZmE5NDI5Nzc1N2Q3OWM5ODdiYTA1ZGZiMDAxYjI1MmM5IiwiaWF0IjoxNzE1NjQxMjA3fQ.g-9_Q14t58emPRLi9Ny1mk4dl4oL6ZMTUU3RuJDx2To'

WEB3_PROVIDER_URI = "http://127.0.0.1:8545"
SMART_CONTRACT_ADDRESS = "0xf702F132F5110f0dFe785A794B09760e684c23EC"
