"OPENAI_API_KEY" = "sk-proj-PBqkrYlM3rgBwkY30VgXT3BlbkFJcgjwEc7iphoznOabKG7e"

"PINATA_API_KEY" = "ad1dc888ebae439749c1"
"PINATA_SECRET_API_KEY" = "af3e94e88286b4403017a9d1d4c402052a17aa33ee03f0d66750796702c0510d"
"PINATA_JWT_TOKEN" = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI1NGUyNzc2Ny0zNWVhLTRmN2MtYjQ0My05ZmNjN2Y3ZTg5YjYiLCJlbWFpbCI6InZhbmdiZUBwcm90b25tYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImlkIjoiRlJBMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfSx7ImlkIjoiTllDMSIsImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxfV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlK...'

WEB3_PROVIDER_URI = "http://127.0.0.1:8545"
SMART_CONTRACT_ADDRESS = "0x6b269d2c87101f0De6576794CA6AcAb582B19f69"
